#!/usr/bin/env bash
readonly mvn_version=3.3.9
readonly mvn_ark="${OPENSHIFT_DATA_DIR}maven.tar.gz"
readonly mvn_dir="${OPENSHIFT_DATA_DIR}maven"
readonly jetty_version=9.4.0.v20161208
readonly jetty_ark="${OPENSHIFT_DATA_DIR}jetty.tar.gz"
readonly jetty_dir="${OPENSHIFT_DATA_DIR}jetty"
readonly mvn_xml="${OPENSHIFT_DATA_DIR}maven.xml"
readonly logfile="${OPENSHIFT_LOG_DIR}server.log"

export JAVA_HOME='/etc/alternatives/java_sdk_1.8.0'
export PATH="${JAVA_HOME}/bin:${PATH}"

if [ -d "${mvn_dir}" ] && [ "$(cat ${mvn_dir}/VERSION)" == "${mvn_version}" ]; then
    echo "Maven already installed"
else
    echo "Installing Maven ${mvn_version}"
    if [ -d "${mvn_dir}" ]; then
        rm -rf "${mvn_dir}"
    fi

    curl -o "${mvn_ark}" "http://mirror.nohup.it/apache/maven/maven-3/${mvn_version}/binaries/apache-maven-${mvn_version}-bin.tar.gz"

    mkdir "${mvn_dir}"
    tar -xzf "${mvn_ark}" -C "${mvn_dir}" --strip 1
    rm "${mvn_ark}"
    echo "${mvn_version}" > "${mvn_dir}/VERSION"
fi

if [ -d "${jetty_dir}" ] && [ "$(cat ${jetty_dir}/VERSION)" == "${jetty_version}" ]; then
    echo "Jetty already installed"
else
    echo "Installing Jetty ${jetty_version}"
    if [ -d "${jetty_dir}" ]; then
        rm -rf "${jetty_dir}"
    fi

    curl -o "${jetty_ark}" "http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/${jetty_version}/jetty-distribution-${jetty_version}.tar.gz"

    mkdir "${jetty_dir}"
    tar -xzf "${jetty_ark}" -C "${jetty_dir}" --strip 1
    rm "${jetty_ark}"
    echo "${jetty_version}" > "${jetty_dir}/VERSION"

    rm -f "${jetty_dir}/start.ini"
    rm -rf "${jetty_dir}/start.d"
    (
        cd "${jetty_dir}"
        java -jar start.jar --create-startd --add-to-start=jsp,http,webapp,deploy
    )
    rm -rf "${jetty_dir}/contexts/"*
    rm -rf "${jetty_dir}/webapps"

    echo '<settings>' > "${mvn_xml}"
    echo '  <localRepository>${OPENSHIFT_DATA_DIR}maven</localRepository>' >> "${mvn_xml}"
    echo '</settings>' >> "${mvn_xml}"
fi

readonly pid="$(ps aux | grep [j]etty | awk '{print $2}')"
if [ -n "${pid}" ]; then
    echo "Running process found ${pid}. Killing it..." >> "${logfile}"
    kill "${pid}"
fi

cd "${OPENSHIFT_REPO_DIR}"

"${mvn_dir}/bin/mvn" --global-settings "${OPENSHIFT_DATA_DIR}maven.xml" --version
"${mvn_dir}/bin/mvn" --global-settings "${OPENSHIFT_DATA_DIR}maven.xml" clean package -Popenshift -DskipTests

cd "${OPENSHIFT_DATA_DIR}jetty"

if [ -L webapps ]; then
    rm webapps
else
    rm -rf webapps
fi

ln -s "${OPENSHIFT_REPO_DIR}deployments" webapps

readonly ms="${JAVA_MS-384m}"
readonly mx="${JAVA_MX-412m}"

readonly cmd="java -Xms${ms} -Xmx${mx} -jar start.jar -Djetty.http.host=${OPENSHIFT_DIY_IP} -Djetty.http.port=${OPENSHIFT_DIY_PORT}"
echo "Running command ${cmd}"
nohup ${cmd} >> "${logfile}" 2>&1 &
