#!/usr/bin/env bash
if [ -d "${OPENSHIFT_DATA_DIR}jetty" ] && [ -f "${OPENSHIFT_DATA_DIR}jetty/jetty.pid" ]; then
    cd "${OPENSHIFT_DATA_DIR}jetty"

    if ps -p "$(cat jetty.pid)" >/dev/null
    then
        echo "Terminating running Jetty process $(cat jetty.pid)"
        kill "$(cat jetty.pid)"
    fi
    rm jetty.pid
fi
